#!/usr/bin/env python3
"""Derive one convex body outline per bot from its painted sprite and write
src/core/hulls.js. Run after any sprite or sprite-scale change:

    python3 tools/gen_hulls.py

The outline is in world units, bot centred at the origin, facing right, y down.
It is the single collider the sim uses for terrain, other bots, projectiles
and blasts.
"""
import json, os, cv2, numpy as np
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
man = json.load(open(os.path.join(ROOT, 'art/sprites/manifest.json')))
# world units per sprite "R": botRadius x drawBot scale x visual scale x ART_SCALE
R = 0.5 * 1.67 * 1.25 * 0.78
hulls = {}
for bot, parts in man.items():
    spec = parts['full']
    im = cv2.imread(os.path.join(ROOT, 'art/sprites', spec['file']), cv2.IMREAD_UNCHANGED)
    h, w = im.shape[:2]; alpha = im[:, :, 3]
    wu = R * 2.6 * spec['scale']; hu = wu * h / w; k = wu / w
    mask = (alpha > 40).astype(np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((9, 9), np.uint8))   # drop wisps and antennae
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    hull = cv2.convexHull(np.vstack(cnts))
    poly = cv2.approxPolyDP(hull, 0.035 * max(w, h), True).reshape(-1, 2)
    hulls[bot] = [[round(px * k - wu / 2, 3), round(py * k - hu / 2 + R * spec['dy'], 3)] for px, py in poly]
    xs = [p[0] for p in hulls[bot]]; ys = [p[1] for p in hulls[bot]]
    print(f"{bot:9} {len(poly):2d} pts  x {min(xs):+.2f}..{max(xs):+.2f}  y {min(ys):+.2f}..{max(ys):+.2f}")
js = ("// Generated by tools/gen_hulls.py from art/sprites: one convex outline per bot,\n"
      "// in world units, bot centred at the origin, facing right, y down.\n"
      "export const BOT_HULLS = " + json.dumps(hulls) + ";\n")
open(os.path.join(ROOT, 'src/core/hulls.js'), 'w').write(js)
